# 云原生开发
$:
  vscode:
    - docker:
        image: docker.cnb.cool/magiccode1412/universal/node_20_dev:latest
      services:
        - vscode
        - docker
      # 开发环境启动后会执行的任务
      stages:
        - name: install dependence
          script: bash scripts/install.sh
        - name: install fnpack
          script: |
            cd /root
            curl -fsSL -o fnpack https://static2.fnnas.com/fnpack/fnpack-1.2.1-linux-amd64
            chmod +x fnpack
            mv fnpack /usr/local/bin/fnpack

  push:
  - imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
    stages:
      - name: sync_to_github
        image: tencentcom/git-sync
        settings:
          target_url: https://github.com/${GITHUB_USERNAME}/${CNB_REPO_NAME_LOWERCASE}.git
          auth_type: https
          username: "${GITHUB_USERNAME}"
          password: "${GITHUB_ACCESS_TOKEN}"
          force: true  

main:
  web_trigger_docker_cnb:
    - runner:
        tags: cnb:arch:amd64
      services:
        - docker
      imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      env:
        CNB_IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest-linux-amd64
        DOCKERHUB_IMAGE_TAG: ${DOCKERHUB_USERNAME}/${CNB_REPO_NAME_LOWERCASE}:latest-linux-amd64
      stages:
        - name: docker login
          script: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - name: docker build
          script: docker build -t ${CNB_IMAGE_TAG} .
        - name: docker push
          script: |
            docker push ${CNB_IMAGE_TAG}
            docker tag ${CNB_IMAGE_TAG} ${DOCKERHUB_IMAGE_TAG}
            docker push ${DOCKERHUB_IMAGE_TAG}
        - name: resolve
          type: cnb:resolve
          options:
            key: build-amd64 
          
    - runner:
        tags: cnb:arch:arm64:v8
      services:
        - docker
      imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      env:
        CNB_IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest-linux-arm64
        DOCKERHUB_IMAGE_TAG: ${DOCKERHUB_USERNAME}/${CNB_REPO_NAME_LOWERCASE}:latest-linux-arm64
      stages:
        - name: docker login
          script: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - name: docker build
          script: docker build -t ${CNB_IMAGE_TAG} .
        - name: docker push
          script: |
            docker push ${CNB_IMAGE_TAG}
            docker tag ${CNB_IMAGE_TAG} ${DOCKERHUB_IMAGE_TAG}
            docker push ${DOCKERHUB_IMAGE_TAG}
        - name: resolve
          type: cnb:resolve
          options:
            key: build-arm64

    - services:
        - docker
      imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      env:
        CNB_IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest
        DOCKERHUB_IMAGE_TAG: ${DOCKERHUB_USERNAME}/${CNB_REPO_NAME_LOWERCASE}:latest
      stages:
        - name: await the amd64
          type: cnb:await
          options:
            key: build-amd64
        - name: await the arm64
          type: cnb:await
          options:
            key: build-arm64
        - name: manifest_cnb
          image: cnbcool/manifest
          settings:
            target: ${CNB_IMAGE_TAG}
            template: ${CNB_IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: manifest_dockerhub
          image: cnbcool/manifest
          settings:
            username: ${DOCKERHUB_USERNAME}
            password: ${DOCKERHUB_TOKEN}
            target: ${DOCKERHUB_IMAGE_TAG}
            template: ${DOCKERHUB_IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: remove tag
          type: artifact:remove-tag
          options:
            name: ${CNB_REPO_NAME}
            tags:
              - latest-linux-amd64
              - latest-linux-arm64
            type: docker

dev:
  push:
    - services:
        - docker
      imports: https://cnb.cool/magiccode1412/secret/-/blob/main/env.yml
      stages:
        - name: docker build && push
          script: bash ./scripts/docker.sh dev